spring:
  datasource:
    url: jdbc:mysql://localhost:3306/krankenhaus_db
    username: root
    password: Kecske69!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    profiles:
      active: load_demo_data
server:
  error:
    include-stacktrace: never